In [1]:
import numpy as np

In [2]:
# concatenation and stacking

In [3]:
# joining two or more arrays together making them a array is known as concatenation. The numpy.concatenate() function is used to join two or more arrays of the same shape along a specified axis.

In [4]:
arr1 = np.array([2,4,5,6])
arr2 = np.array([1,3,7,8])

arr = np.concatenate([arr1, arr2])

In [5]:
arr


array([2, 4, 5, 6, 1, 3, 7, 8])

In [6]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr1)
print("\n")
arr2 = np.array([[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


[[16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [7]:
arr = np.concatenate([arr1, arr2])
# arr = np.concatenate([arr1, arr2], axis=1)

In [8]:
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
np.random.seed(40)
arr1=np.random.randint(0,255,size=[5,5])
print(arr1)
print("\n")
arr2=np.random.randint(0,255,size=[4,5]) #you can give row size different thant the first one in case axis=0, but column count should be same.
print(arr2)
arr=np.concatenate([arr1, arr2])

[[ 70 219   7 165 248]
 [184  50 193  12  71]
 [114  19 159  74  55]
 [211 187  91  73 224]
 [ 49 181  73   8 180]]


[[158 207  14  92 244]
 [104 186 202  22 131]
 [219  99 199  55 241]
 [211 253 156 141 165]]


In [17]:
arr

array([[ 70, 219,   7, 165, 248],
       [184,  50, 193,  12,  71],
       [114,  19, 159,  74,  55],
       [211, 187,  91,  73, 224],
       [ 49, 181,  73,   8, 180],
       [158, 207,  14,  92, 244],
       [104, 186, 202,  22, 131],
       [219,  99, 199,  55, 241],
       [211, 253, 156, 141, 165]])

In [33]:
np.random.seed(34)
arr1=np.random.randint(0,255,size=[2,2,2])
print(arr1)
print("\n")
arr2=np.random.randint(0,255,size=[2,2,2])
print(arr2)
arr=np.concatenate([arr1, arr2],axis=2)

[[[161 122]
  [234 105]]

 [[246  85]
  [ 68  35]]]


[[[197 139]
  [234 206]]

 [[157  18]
  [ 29  89]]]


In [34]:
arr

array([[[161, 122, 197, 139],
        [234, 105, 234, 206]],

       [[246,  85, 157,  18],
        [ 68,  35,  29,  89]]])

In [ ]:
#============================ stacking ==============================

In [36]:
np.random.seed(38)
arr1=np.random.randint(0,225,size=[9])
arr2=np.random.randint(0,355,size=[9])

In [37]:
arr1

array([161,  75,  53, 211,  60, 132,   2,  23,  89])

In [38]:
arr2

array([348, 240, 350,  65, 125,  99,  97, 114, 125])

In [43]:
arr = np.stack([arr1, arr2],axis=0) 
# arr = np.stack([arr1, arr2],axis=1)
arr

array([[161,  75,  53, 211,  60, 132,   2,  23,  89],
       [348, 240, 350,  65, 125,  99,  97, 114, 125]])

In [ ]:
# ======  type of stacking  =======
#   1. Horizontal stacking: np.hstack()
#   2. Vertical stacking: np.vstack()

In [44]:
np.random.seed(40)
arr1=np.random.randint(0,50,size=[2,4])
print(arr1)
print("\n")
arr2=np.random.randint(0,100,size=[2,4])
print(arr2)



[[ 6 27  7 37]
 [ 1 12  7 19]]


[[31 74 55 83]
 [59 91 73 96]]


In [49]:
arr = np.hstack([arr1, arr2])

In [50]:
arr

array([[ 6, 27,  7, 37, 31, 74, 55, 83],
       [ 1, 12,  7, 19, 59, 91, 73, 96]])

In [58]:
arr=np.vstack([arr1, arr2])
arr

array([[ 49, 181],
       [ 73,   8],
       [158, 207],
       [270, 104]])

In [ ]:
np.random.seed(34)
# create a 2 random arrays of range 0-255 and shape 2,2 
# and one of range 0-344 and shape 2,2
# join them such that the elemnt of the first array 2d arrays are in concatenation with the second arrays
# and also convert into 1d array

In [52]:
arr1 =np.random.randint(0,255,size=[2,2])
print(arr1)
print(arr1.shape)
print("\n")
arr2 =np.random.randint(0,344,size=[2,2])
print(arr2)
print(arr2.shape)

[[ 49 181]
 [ 73   8]]
(2, 2)


[[158 207]
 [270 104]]
(2, 2)


In [64]:

# arr = np.concatenate([arr1, arr2], axis=0).reshape(-1,)
arr = np.ravel(np.concatenate([arr1, arr2], axis=0))
arr

array([ 49, 181,  73,   8, 158, 207, 270, 104])