In [39]:
import numpy as np
np.random.seed(23)

In [40]:
random = np.random.randint(0,226, size = [6,8])
random

array([[ 83,  40, 201, 182,  31, 204,  91,  39],
       [ 90, 153, 179,   6, 123, 173,  12,  49],
       [194, 203, 213, 197, 192,  12,  21,  48],
       [ 41,  79,  90, 190,  57, 147, 161, 187],
       [ 39, 143,  36,  65, 129, 116, 171,  15],
       [214, 103, 211, 186, 118,  25, 194, 202]])

In [41]:
# random[0:7:5, 0:8:7]
# random[0::5, 0::7]

random[::5, ::7]

array([[ 83,  39],
       [214, 202]])

In [42]:
# find corner elements of the array

In [43]:
random = np.random.randint(0,226, size = [8,10])
random

array([[125,  35, 224,  56,  13,  60,  22, 166,  31,  94],
       [206,   0, 149,   6,  32,  98,  32, 142,  31,  78],
       [211,  80,  70,  66, 210, 213, 183,  27,  62,  43],
       [202,  71, 170, 211,  21,   6,  68, 150,  43, 136],
       [213, 190, 160,  60, 100,  11,   1,  41,  26,  37],
       [169,  56,  39, 209, 160, 181,  35,  23, 106,  29],
       [ 42, 166,   4,  93,  32,  50,  85,  27, 161, 104],
       [ 91, 223, 162,   0, 219, 139,  62, 224, 118, 216]])

In [44]:
row , col = random.shape

In [45]:
random[::row-1, ::col-1]

array([[125,  94],
       [ 91, 216]])

In [46]:
#=============================================================

In [47]:
random = np.random.randint(0,226, size = [8,10])
cal = random
cal

array([[182, 113, 217, 206,  41, 198, 213, 133,   7,   4],
       [144, 102,   9,  56,  48, 111, 171,  62, 198,  31],
       [130,   0,  15,  32, 176,  15,  61, 130,  34,  22],
       [170,  66, 104,  89, 129,  78,  53,  80, 191,  84],
       [ 87,  70, 130, 187, 173,  23,  23,  88,  85, 159],
       [188, 106,   3,  49,  62, 126,   9, 149,  65, 208],
       [ 81, 102,  11,  68,  80, 220, 157,  99,  99, 138],
       [208, 199,  20, 120,  33, 200,  17,   6, 121, 164]])

In [48]:
#==========================================================

In [49]:
# ================= random methods ============

In [50]:
# ---------------->>>>>>   arrange method

arr = np.arange(0,11)
arr.shape

(11,)

In [51]:
new_arr = np.expand_dims(arr, axis = 1)

In [52]:
#---------------->>>>>>    linspace method

arr = np.linspace(2, 7, 20)
arr.shape

(20,)

In [53]:
arr

array([2.        , 2.26315789, 2.52631579, 2.78947368, 3.05263158,
       3.31578947, 3.57894737, 3.84210526, 4.10526316, 4.36842105,
       4.63157895, 4.89473684, 5.15789474, 5.42105263, 5.68421053,
       5.94736842, 6.21052632, 6.47368421, 6.73684211, 7.        ])

In [54]:
# Aggregate methods
random.sum()
random.mean()
random.max()
random.min()
random.std()
random.var()
random.argmax()
random.argmin()

np.int64(21)

In [55]:
random

array([[182, 113, 217, 206,  41, 198, 213, 133,   7,   4],
       [144, 102,   9,  56,  48, 111, 171,  62, 198,  31],
       [130,   0,  15,  32, 176,  15,  61, 130,  34,  22],
       [170,  66, 104,  89, 129,  78,  53,  80, 191,  84],
       [ 87,  70, 130, 187, 173,  23,  23,  88,  85, 159],
       [188, 106,   3,  49,  62, 126,   9, 149,  65, 208],
       [ 81, 102,  11,  68,  80, 220, 157,  99,  99, 138],
       [208, 199,  20, 120,  33, 200,  17,   6, 121, 164]])

In [56]:
# ---------------->>>>>>   vectorization method


np.random.seed(56)
random = np.random.randint(0,225,size = [3,7])
random

array([[ 85, 143, 192, 162, 122, 142,  87],
       [ 22, 100, 185,  90,  55, 111, 113],
       [152, 140, 194,  43,  11, 110,  80]])

In [59]:
arr2 = np.array([[1],[0],[1]])
arr2

array([[1],
       [0],
       [1]])

In [61]:
random*arr2

array([[ 85, 143, 192, 162, 122, 142,  87],
       [  0,   0,   0,   0,   0,   0,   0],
       [152, 140, 194,  43,  11, 110,  80]])

In [69]:
print("addition ==> \n",random+arr2)
print("\n")
print("substraction ==> \n",random-arr2)
print("\n")
print(random**arr2)

addition ==> 
 [[ 1 11 21 31 41 51 61]
 [ 0 10 20 30 40 50 60]
 [ 1 11 21 31 41 51 61]]


substraction ==> 
 [[-1  9 19 29 39 49 59]
 [ 0 10 20 30 40 50 60]
 [-1  9 19 29 39 49 59]]


[[ 0 10 20 30 40 50 60]
 [ 1  1  1  1  1  1  1]
 [ 0 10 20 30 40 50 60]]


In [71]:
arr3 = np.array([0,0,1,1,0,0,1])
arr3

array([0, 0, 1, 1, 0, 0, 1])