In [55]:
import numpy as np

In [56]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr = np.arange(1,13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
print("shape :",arr.shape)
print("size :", arr.size)
print("dimensions :", arr.ndim)
print("data type :", arr.dtype)

shape : (3, 4)
size : 12
dimensions : 2
data type : int64


In [59]:
# arr1 = np.array([[0,0,0],[0,0,0],[0,0,0]])
# arr2 = np.array([[1,1,1],[1,1,1],[1,1,1]])
# print(arr1)
# print(arr2)

zeros = np.zeros((4,4))
ones = np.ones((3,5))
print(zeros)
print("\n")
print(ones)


print("\n")
twos = np.full((3,3),2)
print(twos)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [60]:
arr_even = np.arange(2,51,2)
arr_even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

In [64]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
matrix = arr.reshape(3,4)
print(matrix)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [66]:
array = np.random.randint(1,101,10)
array

array([45, 39, 53,  4,  1, 56, 22, 22, 74, 39])

In [68]:
array = np.random.rand(5)
array

array([0.61252534, 0.26647378, 0.64391427, 0.8110621 , 0.01902474])