In [ ]:
import numpy as np

# ============== random methods ============

In [ ]:
# rand method generates random numbers between 0 and 1. 
# It takes the shape of the array as an argument.

np.random.seed(34)
random = np.random.rand(4,5)

In [6]:
random

array([[0.03856168, 0.78010046, 0.09270376, 0.63289269, 0.01389085],
       [0.93615854, 0.42657438, 0.25308645, 0.18996531, 0.41482463],
       [0.01342061, 0.64847278, 0.86936875, 0.6090357 , 0.80799282],
       [0.82651133, 0.27168333, 0.83647644, 0.28254136, 0.1383086 ]])

In [ ]:
# randn method generates random numbers from a standard normal 
# distribution. It takes the shape of the array as an argument.

random = np.random.randn(4,5)

In [8]:
random.mean()

np.float64(-0.010845953119799568)

In [ ]:
random = np.random.normal(233,23,5) # normal_location, std, no_of_values
random

array([206.71226915, 237.9638496 , 254.28894725, 242.36570128,
       245.82678375])

In [ ]:
random = np.random.randint(0,225,size=[3,4]) #start, stop , size = [row, col]
random

array([[  6,  59,  77, 157],
       [191,  17, 223,   0],
       [ 85, 102, 103,  43]])

In [12]:
np.random.seed(34)
marks = np.random.randint(0,101,size=[6,7])

In [13]:
mean_marks = marks.mean() 

In [14]:
idx,idy = np.where(marks >= mean_marks) #it returns row and column index

In [15]:
marks[idx,idy] #it returns the values of marks which are greater than mean_marks

array([85, 68, 69, 78, 89, 96, 62, 85, 63, 72, 84, 72, 77, 98, 58, 75, 58,
       62, 88, 66, 70])

In [17]:
marks = np.where(marks >= mean_marks, "Pass","Fail")
marks

array([['Fail', 'Pass', 'Pass', 'Fail', 'Pass', 'Fail', 'Pass'],
       ['Fail', 'Fail', 'Fail', 'Pass', 'Fail', 'Fail', 'Pass'],
       ['Pass', 'Fail', 'Fail', 'Fail', 'Fail', 'Pass', 'Fail'],
       ['Pass', 'Pass', 'Fail', 'Pass', 'Pass', 'Pass', 'Fail'],
       ['Fail', 'Fail', 'Pass', 'Pass', 'Fail', 'Pass', 'Fail'],
       ['Pass', 'Pass', 'Fail', 'Pass', 'Pass', 'Pass', 'Fail']],
      dtype='<U4')

In [ ]:
#Take a random array and filter out the values from it that are divisible by 9

In [19]:
np.random.seed(56)
random = np.random.randint(0,256,size=[7,7])
random

array([[ 85, 228, 143, 192, 162, 235, 122],
       [142, 233, 251,  87,  22, 100, 185],
       [ 90,  55, 111, 113, 152, 140, 194],
       [254,  43,  11, 110,  80, 245, 230],
       [161,  89,  10,  31, 156, 165, 245],
       [162,  15, 156,  89,  19,  69, 169],
       [194,  74,  65,  16,  13,  20, 230]])

In [ ]:
#Shapes
#Dimension 
#Formation Of Multidimensional arrays
#Reshaping
#Indexing, Slicing
#Concatenate
#stack, hstack, vstack
#where
#ravel and flatten
#astype
#split, hsplit, vsplit

In [20]:
np.random.seed(34)
random = np.random.randint(0,256, size = [6,6])
random

array([[161, 122, 234, 105, 246,  85],
       [ 68,  35, 197, 139, 234, 206],
       [157,  18,  29,  89, 248,  29],
       [102, 117, 118,  20, 229,  96],
       [ 62,   5, 148, 179,  19, 213],
       [ 21, 191, 232,  72, 239,  42]])

In [22]:
splitted = np.split(random, 3, axis = 1) #axis = 0 for row wise and axis = 1 for column wise

In [23]:
horizontal_split = np.hsplit(random, 3) #axis = 0 for row wise and axis = 1 for column wise

In [24]:
horizontal_split

[array([[161, 122],
        [ 68,  35],
        [157,  18],
        [102, 117],
        [ 62,   5],
        [ 21, 191]]),
 array([[234, 105],
        [197, 139],
        [ 29,  89],
        [118,  20],
        [148, 179],
        [232,  72]]),
 array([[246,  85],
        [234, 206],
        [248,  29],
        [229,  96],
        [ 19, 213],
        [239,  42]])]

In [32]:
vertical_split = np.vsplit(random,2)

In [30]:
vertical_split

[array([[161, 122, 234, 105, 246,  85],
        [ 68,  35, 197, 139, 234, 206],
        [157,  18,  29,  89, 248,  29]]),
 array([[102, 117, 118,  20, 229,  96],
        [ 62,   5, 148, 179,  19, 213],
        [ 21, 191, 232,  72, 239,  42]])]

In [33]:
ramdom = np.random.randint(0,225, size = [30,40])
random

array([[161, 122, 234, 105, 246,  85],
       [ 68,  35, 197, 139, 234, 206],
       [157,  18,  29,  89, 248,  29],
       [102, 117, 118,  20, 229,  96],
       [ 62,   5, 148, 179,  19, 213],
       [ 21, 191, 232,  72, 239,  42]])

In [ ]:
# stride slicing

row , col = ramdom.shape
row_n = row - 1
col_n = col - 1
for i in range(row_n):
    for j in range(col_n):
        print(random[i:i+2,j:j+2])
        print("\n")

[[161 122]
 [ 68  35]]


[[122 234]
 [ 35 197]]


[[234 105]
 [197 139]]


[[105 246]
 [139 234]]


[[246  85]
 [234 206]]


[[ 85]
 [206]]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[[ 68  35]
 [157  18]]


[[ 35 197]
 [ 18  29]]


[[197 139]
 [ 29  89]]


[[139 234]
 [ 89 248]]


[[234 206]
 [248  29]]


[[206]
 [ 29]]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[[157  18]
 [102 117]]


[[ 18  29]
 [117 118]]


[[ 29  89]
 [118  20]]


[[ 89 248]
 [ 20 229]]


[[248  29]
 [229  96]]


[[29]
 [96]]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[]


[[102 117]
 [ 62   5]]


[[117 118]
 [  5 148]]


[[118  20]
 [148 179]]


[[ 20 

In [3]:
import numpy as np
np.random.seed(23)

In [10]:
random = np.random.randint(0,226, size = [6,8])
random

array([[ 68, 150,  43, 136, 213, 190, 160,  60],
       [100,  11,   1,  41,  26,  37, 169,  56],
       [ 39, 209, 160, 181,  35,  23, 106,  29],
       [ 42, 166,   4,  93,  32,  50,  85,  27],
       [161, 104,  91, 223, 162,   0, 219, 139],
       [ 62, 224, 118, 216, 182, 113, 217, 206]])

In [19]:
random[0:7:5, 0:8:7]

array([[ 68,  60],
       [ 62, 206]])