In [30]:
import numpy as np


In [31]:
# ================================ index and slicing =============================

In [32]:
np.random.seed(45)
random = np.random.randint(0, 225, size=[5,6])
random

array([[203, 158, 131, 124,  32,  95],
       [189, 213, 163,  68, 121, 120],
       [ 15,  65, 142,  53,  57, 118],
       [200, 215,  46,   8, 181, 140],
       [162, 124,  24,  12,  17, 196]])

In [33]:
random[1:4:2, 1:5:2]


array([[213,  68],
       [215,   8]])

In [34]:
random[1,1]

np.int64(213)

In [35]:
np.random.seed(45)
random = np.random.randint(0, 225, size=[5,6])
random

array([[203, 158, 131, 124,  32,  95],
       [189, 213, 163,  68, 121, 120],
       [ 15,  65, 142,  53,  57, 118],
       [200, 215,  46,   8, 181, 140],
       [162, 124,  24,  12,  17, 196]])

In [36]:
random[1:4,1::2]

array([[213,  68, 120],
       [ 65,  53, 118],
       [215,   8, 140]])

In [37]:
random[1:4,:5:2]

array([[189, 163, 121],
       [ 15, 142,  57],
       [200,  46, 181]])

In [ ]:
# reversed slicing

np.random.seed(45)
random = np.random.randint(0, 225, size=[5,6])
random

array([[203, 158, 131, 124,  32,  95],
       [189, 213, 163,  68, 121, 120],
       [ 15,  65, 142,  53,  57, 118],
       [200, 215,  46,   8, 181, 140],
       [162, 124,  24,  12,  17, 196]])

In [42]:
random[3:0:-1,3:0:-1]

array([[  8,  46, 215],
       [ 53, 142,  65],
       [ 68, 163, 213]])

In [43]:
np.random.seed(45)
random = np.random.randint(0, 225, size=[5,6])
random

array([[203, 158, 131, 124,  32,  95],
       [189, 213, 163,  68, 121, 120],
       [ 15,  65, 142,  53,  57, 118],
       [200, 215,  46,   8, 181, 140],
       [162, 124,  24,  12,  17, 196]])

In [62]:
random[1:4,0:3]

array([[189, 213, 163],
       [ 15,  65, 142],
       [200, 215,  46]])

In [ ]:
# revesed with negative indexing

random[-2:-5:-1,-4::-1]

array([[ 46, 215, 200],
       [142,  65,  15],
       [163, 213, 189]])

In [66]:
# concatenation 

arr1 = random[0:3,0:3]
arr1

array([[203, 158, 131],
       [189, 213, 163],
       [ 15,  65, 142]])

In [68]:
arr2 = random[2:5,2:5]
arr2

array([[142,  53,  57],
       [ 46,   8, 181],
       [ 24,  12,  17]])

In [69]:
arr = np.concatenate((arr1, arr2), axis=0)
arr

array([[203, 158, 131],
       [189, 213, 163],
       [ 15,  65, 142],
       [142,  53,  57],
       [ 46,   8, 181],
       [ 24,  12,  17]])