In [7]:
import numpy as np

In [8]:
np.random.seed(67)
random = np.random.randint(0,255, size=[4,4])

In [9]:
random

array([[ 67,  53, 202, 197],
       [  7, 217, 137,  91],
       [ 35,  22, 217,  45],
       [ 35,  23, 104, 181]])

In [10]:
(2,3)

(2, 3)

In [12]:
rows , cols = random.shape

In [13]:
#creating strides of 2x2
for i in range(rows-1):
    for j in range(cols-1):
        print(random[i:i+2, j:j+2])

[[ 67  53]
 [  7 217]]
[[ 53 202]
 [217 137]]
[[202 197]
 [137  91]]
[[  7 217]
 [ 35  22]]
[[217 137]
 [ 22 217]]
[[137  91]
 [217  45]]
[[35 22]
 [35 23]]
[[ 22 217]
 [ 23 104]]
[[217  45]
 [104 181]]


In [16]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
# Reshaping: changing the shape (number of rows and columns)
# of an multidimensional array is known as reshaping 

In [17]:
np.random.seed(45)
random = np.random.randint(0,225,size=[5,8])

In [18]:
random

array([[203, 158, 131, 124,  32,  95, 189, 213],
       [163,  68, 121, 120,  15,  65, 142,  53],
       [ 57, 118, 200, 215,  46,   8, 181, 140],
       [162, 124,  24,  12,  17, 196, 110, 126],
       [158,  56,  14,  36,  31,  86, 164, 185]])

In [19]:
random.reshape(1,-1)

array([[203, 158, 131, 124,  32,  95, 189, 213, 163,  68, 121, 120,  15,
         65, 142,  53,  57, 118, 200, 215,  46,   8, 181, 140, 162, 124,
         24,  12,  17, 196, 110, 126, 158,  56,  14,  36,  31,  86, 164,
        185]])

In [20]:
random.reshape(1,-1)#make sure the reshape value when multiplied should be equal to the number of elements in array

array([[203, 158, 131, 124,  32,  95, 189, 213, 163,  68, 121, 120,  15,
         65, 142,  53,  57, 118, 200, 215,  46,   8, 181, 140, 162, 124,
         24,  12,  17, 196, 110, 126, 158,  56,  14,  36,  31,  86, 164,
        185]])